/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ClientObjectSpawner")]
    [LuaRegisterType(0x4ab816a148604467, typeof(LuaBehaviour))]
    public class ClientObjectSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3e13235dce9da24688a60beb0645b0f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.BoxCollider> m_SpawnZones = default;
        [SerializeField] public UnityEngine.GameObject m_BeePrefab = default;
        [SerializeField] public UnityEngine.GameObject m_HoneyPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SpawnZones),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_BeePrefab),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_HoneyPrefab),
            };
        }
    }
}

#endif
