/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectibleObject")]
    [LuaRegisterType(0x16342f19b0e5d63f, typeof(LuaBehaviour))]
    public class CollectibleObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d61eee943193f614d8af489e32a869f9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_objectType = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_objectType),
            };
        }
    }
}

#endif
