/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TapConnector")]
    [LuaRegisterType(0xf01a2fab1b302e3d, typeof(LuaBehaviour))]
    public class TapConnector : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8ba11a57441c4d64fb098cbfa0511ff1";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_role = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_role),
            };
        }
    }
}

#endif
