/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "623d4d3278a4f45419142d2c5665b89a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_TokenDisplayObject = default;
        [SerializeField] public UnityEngine.GameObject m_BeeCollectionUiObject = default;
        [SerializeField] public UnityEngine.GameObject m_HoneyPanicUiObject = default;
        [SerializeField] public UnityEngine.GameObject m_RoundOverUiObject = default;
        [SerializeField] public UnityEngine.GameObject m_UpgradesDisplayUiObject = default;
        [SerializeField] public UnityEngine.GameObject m_RewardsWheelObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_TokenDisplayObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_BeeCollectionUiObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_HoneyPanicUiObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_RoundOverUiObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_UpgradesDisplayUiObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_RewardsWheelObject),
            };
        }
    }
}

#endif
